// 休闲零食 (catId: 4)
window.PRODUCTS_CAT_4 = [
  { id: 1, catId: 4, subCatId: 404, name: 'Member\'s Mark 每日坚果 900g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/1dt/1.png?raw=true', price: 99, oldPrice: 99, sold: 0, stock: 100, isNew: true },
  { id: 2, catId: 4, subCatId: 404, name: 'NUTHING 开心果裹腰果仁550g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/1dt/2.png?raw=true', price: 79.9, oldPrice: 79.9, sold: 0, stock: 100, isNew: true },
  { id: 3, catId: 4, subCatId: 404, name: 'HRYOUP 苹果干 560g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/1dt/3.png?raw=true', price: 56.9, oldPrice: 56.9, sold: 0, stock: 100, isNew: true },
  { id: 4, catId: 4, subCatId: 405, name: '低脂高蛋白爆汁 鸡胸肉肠 1.1kg', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/2rght/1.png?raw=true', price: 66.9, oldPrice: 66.9, sold: 0, stock: 100, isNew: true },
  { id: 5, catId: 4, subCatId: 405, name: '有友 脱骨鸭掌（山椒味）600g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/2rght/2.png?raw=true', price: 69.9, oldPrice: 69.9, sold: 0, stock: 100, isNew: true },
  { id: 6, catId: 4, subCatId: 405, name: '卤汁牛腱（原味卤香） 450克', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/2rght/3.png?raw=true', price: 99.9, oldPrice: 99.9, sold: 0, stock: 100, isNew: true },
  { id: 7, catId: 4, subCatId: 406, name: '海盐苏打饼干 1.5kg', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/3bgqq/1.png?raw=true', price: 35.9, oldPrice: 35.9, sold: 0, stock: 100, isNew: true },
  { id: 8, catId: 4, subCatId: 406, name: '牛肉馅酥脆饼干 1kg', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/3bgqq/2.png?raw=true', price: 59.9, oldPrice: 59.9, sold: 0, stock: 100, isNew: true },
  { id: 9, catId: 4, subCatId: 406, name: '黑松露火腿苏打饼干(藜麦奇亚籽风味) 1.16kg', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/3bgqq/3.png?raw=true', price: 39.9, oldPrice: 39.9, sold: 0, stock: 100, isNew: true },
  { id: 10, catId: 4, subCatId: 407, name: '黄油华夫饼(烘烤类糕点) 1.02kg', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/4gdls/1.png?raw=true', price: 49.9, oldPrice: 49.9, sold: 0, stock: 100, isNew: true },
  { id: 11, catId: 4, subCatId: 407, name: '黄油鸡蛋卷 608g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/4gdls/2.png?raw=true', price: 59.8, oldPrice: 59.8, sold: 0, stock: 100, isNew: true },
  { id: 12, catId: 4, subCatId: 407, name: '三明治华夫饼 (咸蛋黄味) 1.02kg', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/4gdls/3.png?raw=true', price: 59.9, oldPrice: 59.9, sold: 0, stock: 100, isNew: true },
  { id: 13, catId: 4, subCatId: 408, name: '蒜味虾片(膨化食品) 300g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/5spph/1.png?raw=true', price: 29.8, oldPrice: 29.8, sold: 0, stock: 100, isNew: true },
  { id: 14, catId: 4, subCatId: 408, name: '卡乐比 泰国进口Jagabee淡盐味薯条600g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/5spph/2.png?raw=true', price: 85.9, oldPrice: 85.9, sold: 0, stock: 100, isNew: true },
  { id: 15, catId: 4, subCatId: 408, name: '劳仑兹诺然兹经典原切原味薯片 400克', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/5spph/3.png?raw=true', price: 39.9, oldPrice: 39.9, sold: 0, stock: 100, isNew: true },
  { id: 16, catId: 4, subCatId: 409, name: '每日黑巧鲜萃黑巧克力制品（香醇榛子味） 195g(15g*13)', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/6qkl/1.png?raw=true', price: 99.9, oldPrice: 99.9, sold: 0, stock: 100, isNew: true },
  { id: 17, catId: 4, subCatId: 409, name: '明治(meiji) 巴旦木夹心巧克力 550g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/6qkl/2.png?raw=true', price: 69.9, oldPrice: 69.9, sold: 0, stock: 100, isNew: true },
  { id: 18, catId: 4, subCatId: 409, name: '费列罗 榛果威化巧克力制品 42粒装 525g', img: 'https://cdn.jsdelivr.net/gh/ftvzrs4ycd-droid/my-shop@main/images/5xiu/6qkl/3.png?raw=true', price: 123, oldPrice: 123, sold: 0, stock: 100, isNew: true },
];
