// ============================================
// 商品数据文件
// 以后加商品、改价格、改库存，都只改这个文件
// ============================================

const TOP_CATEGORIES = [
  { id: 8, name: '餐吧', icon: '🍽️' },
  { id: 1, name: '肉蛋果蔬', icon: '🥐' },
  { id: 2, name: '乳品烘焙', icon: '🥛' },
  { id: 3, name: '速食冷冻', icon: '🍪' },
  { id: 4, name: '休闲零食', icon: '🧊' },
  { id: 5, name: '酒水饮料', icon: '🥬' },
  { id: 6, name: '粮油干货', icon: '🍚' },
  { id: 7, name: '个护美妆', icon: '🧴' },
  { id: 9, name: '母婴玩具', icon: '🧴' },
];

const SUB_CATEGORIES = [
  { id: 801, parentId: 8, name: '全部' },
  { id: 802, parentId: 8, name: '热熟食' },
  { id: 803, parentId: 8, name: '轻食' },
  { id: 804, parentId: 8, name: '甜点' },
  { id: 101, parentId: 1, name: '全部' },
  { id: 102, parentId: 1, name: '水果' },
  { id: 103, parentId: 1, name: '精选蔬菜' },
  { id: 104, parentId: 1, name: '有机蔬菜' },
  { id: 105, parentId: 1, name: '牛肉' },
  { id: 106, parentId: 1, name: '牛排' },
  { id: 107, parentId: 1, name: '海鲜水产' },
  { id: 108, parentId: 1, name: '猪肉' },
  { id: 109, parentId: 1, name: '禽类/蛋' },
  { id: 110, parentId: 1, name: '羊肉' },
  { id: 111, parentId: 1, name: '豆制品' },
  { id: 112, parentId: 1, name: '速冻果蔬' },
  { id: 201, parentId: 2, name: '全部' },
  { id: 202, parentId: 2, name: '面包/点心' },
  { id: 203, parentId: 2, name: '蛋糕' },
  { id: 204, parentId: 2, name: '鲜奶/鲜咖' },
  { id: 205, parentId: 2, name: '常温牛奶' },
  { id: 206, parentId: 2, name: '酸奶/乳酸菌' },
  { id: 207, parentId: 2, name: '冷藏饮品' },
  { id: 208, parentId: 2, name: '常温果汁' },
  { id: 209, parentId: 2, name: '谷物冲调' },
  { id: 210, parentId: 2, name: '黄油/奶酪' },
  { id: 211, parentId: 2, name: '咖啡/茶' },
  { id: 301, parentId: 3, name: '全部' },
  { id: 302, parentId: 3, name: '快手菜' },
  { id: 303, parentId: 3, name: '速食肉制品' },
  { id: 304, parentId: 3, name: '香肠/火腿' },
  { id: 305, parentId: 3, name: '熟食' },
  { id: 306, parentId: 3, name: '佐餐速食' },
  { id: 307, parentId: 3, name: '冰淇淋/甜品' },
  { id: 308, parentId: 3, name: '冷冻面点' },
  { id: 309, parentId: 3, name: '火锅丸滑' },
  { id: 310, parentId: 3, name: '冷冻果蔬' },
  { id: 311, parentId: 3, name: '冷冻肉禽' },
  { id: 312, parentId: 3, name: '冷冻水产' },
  { id: 401, parentId: 4, name: '全部' },
  { id: 402, parentId: 4, name: '低糖/低Gl' },
  { id: 403, parentId: 4, name: '月饼/礼盒' },
  { id: 404, parentId: 4, name: '坚果蜜钱' },
  { id: 405, parentId: 4, name: '肉干海苔' },
  { id: 406, parentId: 4, name: '饼干曲奇' },
  { id: 407, parentId: 4, name: '糕点零食' },
  { id: 408, parentId: 4, name: '薯片膨化' },
  { id: 409, parentId: 4, name: '巧克力' },
  { id: 410, parentId: 4, name: '糖果/果冻' },
  { id: 411, parentId: 4, name: '方便食品' },
  { id: 412, parentId: 4, name: '即食甜品' },
  { id: 501, parentId: 5, name: '全部' },
  { id: 502, parentId: 5, name: '啤酒' },
  { id: 503, parentId: 5, name: '果酒/预调' },
  { id: 504, parentId: 5, name: '清酒' },
  { id: 505, parentId: 5, name: '果汁/植物饮' },
  { id: 506, parentId: 5, name: '咖啡/茶饮' },
  { id: 507, parentId: 5, name: '饮用水' },
  { id: 508, parentId: 5, name: '碳酸饮料' },
  { id: 601, parentId: 6, name: '全部' },
  { id: 602, parentId: 6, name: '一酱成菜' },
  { id: 603, parentId: 6, name: '大米面粉' },
  { id: 604, parentId: 6, name: '五谷杂粮' },
  { id: 605, parentId: 6, name: '食用油' },
  { id: 606, parentId: 6, name: '南北干货' },
  { id: 607, parentId: 6, name: '燕窝滋补' },
  { id: 608, parentId: 6, name: '罐头/酱菜' },
  { id: 609, parentId: 6, name: '调味酱汁' },
  { id: 610, parentId: 6, name: '酱油/醋' },
  { id: 611, parentId: 6, name: '盐糖调料' },
  { id: 701, parentId: 7, name: '全部' },
  { id: 702, parentId: 7, name: '秋冬润护' },
  { id: 703, parentId: 7, name: '面部护理' },
  { id: 704, parentId: 7, name: '洗发护发' },
  { id: 705, parentId: 7, name: '身体护理' },
  { id: 706, parentId: 7, name: '口腔健康' },
  { id: 707, parentId: 7, name: '个人清洁' },
  { id: 708, parentId: 7, name: '女性护理' },
  { id: 709, parentId: 7, name: '儿童/男士' },
  { id: 710, parentId: 7, name: '彩妆/香氛' },
  { id: 901, parentId: 9, name: '婴幼儿配方乳粉' },
  { id: 902, parentId: 9, name: '面部护理' },
  { id: 903, parentId: 9, name: '洗发护发' },
  { id: 904, parentId: 9, name: '身体护理' },
  { id: 905, parentId: 9, name: '口腔健康' },
  { id: 906, parentId: 9, name: '个人清洁' },
  { id: 907, parentId: 9, name: '女性护理' },
  { id: 908, parentId: 9, name: '儿童/男士' },
  { id: 909, parentId: 9, name: '彩妆/香氛' },

  
];let PRODUCTS = [];
const LOADED_CATS = {};

